### ISSUE TITLE
Node List: support rendering Plotly images

### ISSUE THREAD

**Issue by nokome** [stencila/designa#122]
One of the mimetypes used as an output of Jupyter Notebooks is [application/vnd.plotly.v1+json](https://jupyter.readthedocs.io/en/latest/reference/mimetype.html#listing-of-custom-mimetypes-used-for-display), for the [Plotly JSON Schema](https://plotly.com/chart-studio-help/json-chart-schema/). This output has widespread use in Jupyter Notebooks and as such is a high priority for support.

I am presently working on support in Encoda but to support interactive Plotly figures in the browser we should add support here too. That work in Encoda will help shape the design of the necessary web component but whatever that is, it will require integration of the [Plotly.js package](https://plotly.com/javascript/).

This is a similar issue to #119 in that it adds support for another code chunk output type.

**Comment by alex-ketch** [comment]
Unfortunately making use plotly.js is proving less straightforward than I hoped @nokome.
Due to issues with [how it's packaged](https://github.com/plotly/plotly.js/issues/3518) and old D3 versions, getting it working with modules/NPM imports isn't working.
[The package size](https://bundlephobia.com/result?p=plotly.js@1.57.1) is also very large, so I don't want to include a blocking script tag everywhere any, even unrelated, Stencila components are used.

Instead I think a better and immediate solution would be to write a script loader shim. It would be run whenever the Plotly component is first referenced, pausing rendering of the component until dynamically loading of the script from a CDN is finished.

**Comment by nokome** [comment]
Uurgh, sorry to hear that @alex-ketch. 

I thought that the bundle size would be large but hoped that code splitting would mean it would only be downloaded on demand, when needed. I certainly agree that we should not add a script tag everywhere. The script loader sound like a good solution though :+1:

**Comment by alex-ketch** [comment]
Closed by https://github.com/stencila/designa/pull/123
